### ISSUE TITLE
websocketでルーム作る

### ISSUE THREAD

**Issue by hirakuuuu** [KateSawada/jmac_sdk#3]
# ゴール

以下の条件を満たす

- サーバーでプログラム起動
- クライアントのプログラムを `$ python [client.py](http://client.py) --room 12345` のように起動して指定したルームに接続
- サーバーは，ルームごとに接続されているクライアントのリストを保持する
    - 例
        
        ```python
        clients = {
        	12345: ["client1", "client2"]
        	98765: ["client0", "client1", "client1"]
        }
        ```
        
- サーバーは，roomIdを指定することで，同じルームに入っているクライアント全てに対してjsonを送ることができる(サーバー側で `send_json_to_room(roomId, json)` によってルーム内すべてのクライアントにjsonを送れる or クライアント側で `on_received_json(json)` 内で自分のルームに対するメッセージのみを識別できる)
- サーバーは，roomIdとクライアントを指定することで，特定のルームの特定のクライアントのみにjsonを送れる or クラアントは自分のみに宛てたjsonを識別できる
- 同時に複数のルームを同時並行で動かすことができる

**Comment by KateSawada** [comment]
#4
